from app.questions.registry import register
from app.questions.schema import Question, TestCase

register(
    Question(
        id="total_revenue_per_product",
        title="Total Revenue per Product",
        difficulty="Medium",
        description="""
Calculate the total revenue generated by each product.

Write a query to join orders and products, then calculate the total revenue (price * quantity) for each product.
Expected columns: `product_name`, `total_revenue`
        """,
        hint="Use JOIN between orders and products, then SUM(price * quantity) with GROUP BY product name.",
        reference_query="SELECT p.name as product_name, SUM(o.quantity * p.price) as total_revenue FROM orders o JOIN products p ON o.product_id = p.id GROUP BY p.name;",
        test_cases=[
            TestCase(
                description="must return at least 1 row",
                validator=lambda rows: len(rows) > 0,
            ),
            TestCase(
                description="each row must have 2 columns",
                validator=lambda rows: (
                    all(len(row) == 2 for row in rows) if rows else False
                ),
            ),
        ],
    )
)
